/* 
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PushApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PushApiTests
    {
        private PushApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PushApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PushApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PushApi
            //Assert.IsInstanceOfType(typeof(PushApi), instance, "instance is a PushApi");
        }

        /// <summary>
        /// Test AddApp
        /// </summary>
        [Test]
        public void AddAppTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MobileAppRequest body = null;
            //var response = instance.AddApp(body);
            //Assert.IsInstanceOf<TemplateIdResponse> (response, "response is TemplateIdResponse");
        }
        /// <summary>
        /// Test AddPushTemplate
        /// </summary>
        [Test]
        public void AddPushTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PushTemplateRequest body = null;
            //var response = instance.AddPushTemplate(body);
            //Assert.IsInstanceOf<TemplateIdResponse> (response, "response is TemplateIdResponse");
        }
        /// <summary>
        /// Test DeleteApp
        /// </summary>
        [Test]
        public void DeleteAppTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DeleteApp(id);
            
        }
        /// <summary>
        /// Test DeletePushTemplate
        /// </summary>
        [Test]
        public void DeletePushTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DeletePushTemplate(id);
            
        }
        /// <summary>
        /// Test ListApp
        /// </summary>
        [Test]
        public void ListAppTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ListApp(id);
            //Assert.IsInstanceOf<MobileAppIdResponse> (response, "response is MobileAppIdResponse");
        }
        /// <summary>
        /// Test ListApps
        /// </summary>
        [Test]
        public void ListAppsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListApps();
            //Assert.IsInstanceOf<List<MobileAppResponse>> (response, "response is List<MobileAppResponse>");
        }
        /// <summary>
        /// Test ListPushTemplate
        /// </summary>
        [Test]
        public void ListPushTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ListPushTemplate(id);
            //Assert.IsInstanceOf<SinglePushTemplateResponse> (response, "response is SinglePushTemplateResponse");
        }
        /// <summary>
        /// Test ListPushTemplates
        /// </summary>
        [Test]
        public void ListPushTemplatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListPushTemplates();
            //Assert.IsInstanceOf<List<SinglePushTemplateResponse>> (response, "response is List<SinglePushTemplateResponse>");
        }
        /// <summary>
        /// Test SendPushMessages
        /// </summary>
        [Test]
        public void SendPushMessagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Object> body = null;
            //var response = instance.SendPushMessages(body);
            //Assert.IsInstanceOf<List<SendMessageIdResponse>> (response, "response is List<SendMessageIdResponse>");
        }
        /// <summary>
        /// Test UpdateApp
        /// </summary>
        [Test]
        public void UpdateAppTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //MobileAppRequest body = null;
            //var response = instance.UpdateApp(id, body);
            //Assert.IsInstanceOf<MobileAppIdResponse> (response, "response is MobileAppIdResponse");
        }
        /// <summary>
        /// Test UpdatePushTemplate
        /// </summary>
        [Test]
        public void UpdatePushTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //PushTemplateRequest body = null;
            //var response = instance.UpdatePushTemplate(id, body);
            //Assert.IsInstanceOf<SinglePushTemplateResponse> (response, "response is SinglePushTemplateResponse");
        }
    }

}
