/* 
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EmailValidatorResponse
    /// </summary>
    [DataContract]
        public partial class EmailValidatorResponse :  IEquatable<EmailValidatorResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailValidatorResponse" /> class.
        /// </summary>
        /// <param name="emailValid">Email Validation Flag.</param>
        /// <param name="emailTemporary">Temporary Email Validation.</param>
        /// <param name="mx">Temporary Email Validation.</param>
        public EmailValidatorResponse(string emailValid = default(string), string emailTemporary = default(string), string mx = default(string))
        {
            this.EmailValid = emailValid;
            this.EmailTemporary = emailTemporary;
            this.Mx = mx;
        }
        
        /// <summary>
        /// Email Validation Flag
        /// </summary>
        /// <value>Email Validation Flag</value>
        [DataMember(Name="emailValid", EmitDefaultValue=false)]
        public string EmailValid { get; set; }

        /// <summary>
        /// Temporary Email Validation
        /// </summary>
        /// <value>Temporary Email Validation</value>
        [DataMember(Name="emailTemporary", EmitDefaultValue=false)]
        public string EmailTemporary { get; set; }

        /// <summary>
        /// Temporary Email Validation
        /// </summary>
        /// <value>Temporary Email Validation</value>
        [DataMember(Name="mx", EmitDefaultValue=false)]
        public string Mx { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailValidatorResponse {\n");
            sb.Append("  EmailValid: ").Append(EmailValid).Append("\n");
            sb.Append("  EmailTemporary: ").Append(EmailTemporary).Append("\n");
            sb.Append("  Mx: ").Append(Mx).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmailValidatorResponse);
        }

        /// <summary>
        /// Returns true if EmailValidatorResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of EmailValidatorResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailValidatorResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EmailValid == input.EmailValid ||
                    (this.EmailValid != null &&
                    this.EmailValid.Equals(input.EmailValid))
                ) && 
                (
                    this.EmailTemporary == input.EmailTemporary ||
                    (this.EmailTemporary != null &&
                    this.EmailTemporary.Equals(input.EmailTemporary))
                ) && 
                (
                    this.Mx == input.Mx ||
                    (this.Mx != null &&
                    this.Mx.Equals(input.Mx))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EmailValid != null)
                    hashCode = hashCode * 59 + this.EmailValid.GetHashCode();
                if (this.EmailTemporary != null)
                    hashCode = hashCode * 59 + this.EmailTemporary.GetHashCode();
                if (this.Mx != null)
                    hashCode = hashCode * 59 + this.Mx.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
