/* 
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EmailReportResponse
    /// </summary>
    [DataContract]
        public partial class EmailReportResponse :  IEquatable<EmailReportResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailReportResponse" /> class.
        /// </summary>
        /// <param name="groupId">groupId.</param>
        /// <param name="groupName">groupName.</param>
        /// <param name="viewsTotal">viewsTotal.</param>
        /// <param name="viewsUnique">viewsUnique.</param>
        /// <param name="clicksTotal">clicksTotal.</param>
        /// <param name="clicksUnique">clicksUnique.</param>
        /// <param name="metricsTotal">metricsTotal.</param>
        /// <param name="metricsProcessed">metricsProcessed.</param>
        /// <param name="metricsSent">metricsSent.</param>
        /// <param name="eventRemoved">eventRemoved.</param>
        /// <param name="eventSoftBounce">eventSoftBounce.</param>
        /// <param name="eventHardBounce">eventHardBounce.</param>
        /// <param name="timePeriod">timePeriod.</param>
        public EmailReportResponse(string groupId = default(string), string groupName = default(string), int? viewsTotal = default(int?), int? viewsUnique = default(int?), int? clicksTotal = default(int?), int? clicksUnique = default(int?), int? metricsTotal = default(int?), int? metricsProcessed = default(int?), int? metricsSent = default(int?), int? eventRemoved = default(int?), int? eventSoftBounce = default(int?), int? eventHardBounce = default(int?), string timePeriod = default(string))
        {
            this.GroupId = groupId;
            this.GroupName = groupName;
            this.ViewsTotal = viewsTotal;
            this.ViewsUnique = viewsUnique;
            this.ClicksTotal = clicksTotal;
            this.ClicksUnique = clicksUnique;
            this.MetricsTotal = metricsTotal;
            this.MetricsProcessed = metricsProcessed;
            this.MetricsSent = metricsSent;
            this.EventRemoved = eventRemoved;
            this.EventSoftBounce = eventSoftBounce;
            this.EventHardBounce = eventHardBounce;
            this.TimePeriod = timePeriod;
        }
        
        /// <summary>
        /// Gets or Sets GroupId
        /// </summary>
        [DataMember(Name="groupId", EmitDefaultValue=false)]
        public string GroupId { get; set; }

        /// <summary>
        /// Gets or Sets GroupName
        /// </summary>
        [DataMember(Name="groupName", EmitDefaultValue=false)]
        public string GroupName { get; set; }

        /// <summary>
        /// Gets or Sets ViewsTotal
        /// </summary>
        [DataMember(Name="viewsTotal", EmitDefaultValue=false)]
        public int? ViewsTotal { get; set; }

        /// <summary>
        /// Gets or Sets ViewsUnique
        /// </summary>
        [DataMember(Name="viewsUnique", EmitDefaultValue=false)]
        public int? ViewsUnique { get; set; }

        /// <summary>
        /// Gets or Sets ClicksTotal
        /// </summary>
        [DataMember(Name="clicksTotal", EmitDefaultValue=false)]
        public int? ClicksTotal { get; set; }

        /// <summary>
        /// Gets or Sets ClicksUnique
        /// </summary>
        [DataMember(Name="clicksUnique", EmitDefaultValue=false)]
        public int? ClicksUnique { get; set; }

        /// <summary>
        /// Gets or Sets MetricsTotal
        /// </summary>
        [DataMember(Name="metricsTotal", EmitDefaultValue=false)]
        public int? MetricsTotal { get; set; }

        /// <summary>
        /// Gets or Sets MetricsProcessed
        /// </summary>
        [DataMember(Name="metricsProcessed", EmitDefaultValue=false)]
        public int? MetricsProcessed { get; set; }

        /// <summary>
        /// Gets or Sets MetricsSent
        /// </summary>
        [DataMember(Name="metricsSent", EmitDefaultValue=false)]
        public int? MetricsSent { get; set; }

        /// <summary>
        /// Gets or Sets EventRemoved
        /// </summary>
        [DataMember(Name="eventRemoved", EmitDefaultValue=false)]
        public int? EventRemoved { get; set; }

        /// <summary>
        /// Gets or Sets EventSoftBounce
        /// </summary>
        [DataMember(Name="eventSoftBounce", EmitDefaultValue=false)]
        public int? EventSoftBounce { get; set; }

        /// <summary>
        /// Gets or Sets EventHardBounce
        /// </summary>
        [DataMember(Name="eventHardBounce", EmitDefaultValue=false)]
        public int? EventHardBounce { get; set; }

        /// <summary>
        /// Gets or Sets TimePeriod
        /// </summary>
        [DataMember(Name="timePeriod", EmitDefaultValue=false)]
        public string TimePeriod { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailReportResponse {\n");
            sb.Append("  GroupId: ").Append(GroupId).Append("\n");
            sb.Append("  GroupName: ").Append(GroupName).Append("\n");
            sb.Append("  ViewsTotal: ").Append(ViewsTotal).Append("\n");
            sb.Append("  ViewsUnique: ").Append(ViewsUnique).Append("\n");
            sb.Append("  ClicksTotal: ").Append(ClicksTotal).Append("\n");
            sb.Append("  ClicksUnique: ").Append(ClicksUnique).Append("\n");
            sb.Append("  MetricsTotal: ").Append(MetricsTotal).Append("\n");
            sb.Append("  MetricsProcessed: ").Append(MetricsProcessed).Append("\n");
            sb.Append("  MetricsSent: ").Append(MetricsSent).Append("\n");
            sb.Append("  EventRemoved: ").Append(EventRemoved).Append("\n");
            sb.Append("  EventSoftBounce: ").Append(EventSoftBounce).Append("\n");
            sb.Append("  EventHardBounce: ").Append(EventHardBounce).Append("\n");
            sb.Append("  TimePeriod: ").Append(TimePeriod).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmailReportResponse);
        }

        /// <summary>
        /// Returns true if EmailReportResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of EmailReportResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailReportResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GroupId == input.GroupId ||
                    (this.GroupId != null &&
                    this.GroupId.Equals(input.GroupId))
                ) && 
                (
                    this.GroupName == input.GroupName ||
                    (this.GroupName != null &&
                    this.GroupName.Equals(input.GroupName))
                ) && 
                (
                    this.ViewsTotal == input.ViewsTotal ||
                    (this.ViewsTotal != null &&
                    this.ViewsTotal.Equals(input.ViewsTotal))
                ) && 
                (
                    this.ViewsUnique == input.ViewsUnique ||
                    (this.ViewsUnique != null &&
                    this.ViewsUnique.Equals(input.ViewsUnique))
                ) && 
                (
                    this.ClicksTotal == input.ClicksTotal ||
                    (this.ClicksTotal != null &&
                    this.ClicksTotal.Equals(input.ClicksTotal))
                ) && 
                (
                    this.ClicksUnique == input.ClicksUnique ||
                    (this.ClicksUnique != null &&
                    this.ClicksUnique.Equals(input.ClicksUnique))
                ) && 
                (
                    this.MetricsTotal == input.MetricsTotal ||
                    (this.MetricsTotal != null &&
                    this.MetricsTotal.Equals(input.MetricsTotal))
                ) && 
                (
                    this.MetricsProcessed == input.MetricsProcessed ||
                    (this.MetricsProcessed != null &&
                    this.MetricsProcessed.Equals(input.MetricsProcessed))
                ) && 
                (
                    this.MetricsSent == input.MetricsSent ||
                    (this.MetricsSent != null &&
                    this.MetricsSent.Equals(input.MetricsSent))
                ) && 
                (
                    this.EventRemoved == input.EventRemoved ||
                    (this.EventRemoved != null &&
                    this.EventRemoved.Equals(input.EventRemoved))
                ) && 
                (
                    this.EventSoftBounce == input.EventSoftBounce ||
                    (this.EventSoftBounce != null &&
                    this.EventSoftBounce.Equals(input.EventSoftBounce))
                ) && 
                (
                    this.EventHardBounce == input.EventHardBounce ||
                    (this.EventHardBounce != null &&
                    this.EventHardBounce.Equals(input.EventHardBounce))
                ) && 
                (
                    this.TimePeriod == input.TimePeriod ||
                    (this.TimePeriod != null &&
                    this.TimePeriod.Equals(input.TimePeriod))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GroupId != null)
                    hashCode = hashCode * 59 + this.GroupId.GetHashCode();
                if (this.GroupName != null)
                    hashCode = hashCode * 59 + this.GroupName.GetHashCode();
                if (this.ViewsTotal != null)
                    hashCode = hashCode * 59 + this.ViewsTotal.GetHashCode();
                if (this.ViewsUnique != null)
                    hashCode = hashCode * 59 + this.ViewsUnique.GetHashCode();
                if (this.ClicksTotal != null)
                    hashCode = hashCode * 59 + this.ClicksTotal.GetHashCode();
                if (this.ClicksUnique != null)
                    hashCode = hashCode * 59 + this.ClicksUnique.GetHashCode();
                if (this.MetricsTotal != null)
                    hashCode = hashCode * 59 + this.MetricsTotal.GetHashCode();
                if (this.MetricsProcessed != null)
                    hashCode = hashCode * 59 + this.MetricsProcessed.GetHashCode();
                if (this.MetricsSent != null)
                    hashCode = hashCode * 59 + this.MetricsSent.GetHashCode();
                if (this.EventRemoved != null)
                    hashCode = hashCode * 59 + this.EventRemoved.GetHashCode();
                if (this.EventSoftBounce != null)
                    hashCode = hashCode * 59 + this.EventSoftBounce.GetHashCode();
                if (this.EventHardBounce != null)
                    hashCode = hashCode * 59 + this.EventHardBounce.GetHashCode();
                if (this.TimePeriod != null)
                    hashCode = hashCode * 59 + this.TimePeriod.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
