/* 
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The header options of the message.
    /// </summary>
    [DataContract]
        public partial class HeaderOptionsRequest :  IEquatable<HeaderOptionsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeaderOptionsRequest" /> class.
        /// </summary>
        /// <param name="listUnsubscribe">gives the recipient the option to unsubscribe. (default to false).</param>
        /// <param name="optInIpAddress">address for the recipient to subscribe to (if he so chooses). (required).</param>
        public HeaderOptionsRequest(bool? listUnsubscribe = false, string optInIpAddress = default(string))
        {
            // to ensure "optInIpAddress" is required (not null)
            if (optInIpAddress == null)
            {
                throw new InvalidDataException("optInIpAddress is a required property for HeaderOptionsRequest and cannot be null");
            }
            else
            {
                this.OptInIpAddress = optInIpAddress;
            }
            // use default value if no "listUnsubscribe" provided
            if (listUnsubscribe == null)
            {
                this.ListUnsubscribe = false;
            }
            else
            {
                this.ListUnsubscribe = listUnsubscribe;
            }
        }
        
        /// <summary>
        /// gives the recipient the option to unsubscribe.
        /// </summary>
        /// <value>gives the recipient the option to unsubscribe.</value>
        [DataMember(Name="listUnsubscribe", EmitDefaultValue=false)]
        public bool? ListUnsubscribe { get; set; }

        /// <summary>
        /// address for the recipient to subscribe to (if he so chooses).
        /// </summary>
        /// <value>address for the recipient to subscribe to (if he so chooses).</value>
        [DataMember(Name="optInIpAddress", EmitDefaultValue=false)]
        public string OptInIpAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HeaderOptionsRequest {\n");
            sb.Append("  ListUnsubscribe: ").Append(ListUnsubscribe).Append("\n");
            sb.Append("  OptInIpAddress: ").Append(OptInIpAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HeaderOptionsRequest);
        }

        /// <summary>
        /// Returns true if HeaderOptionsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of HeaderOptionsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HeaderOptionsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ListUnsubscribe == input.ListUnsubscribe ||
                    (this.ListUnsubscribe != null &&
                    this.ListUnsubscribe.Equals(input.ListUnsubscribe))
                ) && 
                (
                    this.OptInIpAddress == input.OptInIpAddress ||
                    (this.OptInIpAddress != null &&
                    this.OptInIpAddress.Equals(input.OptInIpAddress))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ListUnsubscribe != null)
                    hashCode = hashCode * 59 + this.ListUnsubscribe.GetHashCode();
                if (this.OptInIpAddress != null)
                    hashCode = hashCode * 59 + this.OptInIpAddress.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
