/* 
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// the device ids to send the push message.
    /// </summary>
    [DataContract]
        public partial class ToPushAlertObject :  IEquatable<ToPushAlertObject>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ToPushAlertObject" /> class.
        /// </summary>
        /// <param name="device">the device id of the recipient. (required).</param>
        /// <param name="mergeTags">mergeTags.</param>
        public ToPushAlertObject(string device = default(string), List<ToPushAlertObjectMergeTags> mergeTags = default(List<ToPushAlertObjectMergeTags>))
        {
            // to ensure "device" is required (not null)
            if (device == null)
            {
                throw new InvalidDataException("device is a required property for ToPushAlertObject and cannot be null");
            }
            else
            {
                this.Device = device;
            }
            this.MergeTags = mergeTags;
        }
        
        /// <summary>
        /// the device id of the recipient.
        /// </summary>
        /// <value>the device id of the recipient.</value>
        [DataMember(Name="device", EmitDefaultValue=false)]
        public string Device { get; set; }

        /// <summary>
        /// Gets or Sets MergeTags
        /// </summary>
        [DataMember(Name="mergeTags", EmitDefaultValue=false)]
        public List<ToPushAlertObjectMergeTags> MergeTags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ToPushAlertObject {\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("  MergeTags: ").Append(MergeTags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ToPushAlertObject);
        }

        /// <summary>
        /// Returns true if ToPushAlertObject instances are equal
        /// </summary>
        /// <param name="input">Instance of ToPushAlertObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ToPushAlertObject input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Device == input.Device ||
                    (this.Device != null &&
                    this.Device.Equals(input.Device))
                ) && 
                (
                    this.MergeTags == input.MergeTags ||
                    this.MergeTags != null &&
                    input.MergeTags != null &&
                    this.MergeTags.SequenceEqual(input.MergeTags)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Device != null)
                    hashCode = hashCode * 59 + this.Device.GetHashCode();
                if (this.MergeTags != null)
                    hashCode = hashCode * 59 + this.MergeTags.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
