/* 
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ManualEmail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ManualEmailTests
    {
        // TODO uncomment below to declare an instance variable for ManualEmail
        //private ManualEmail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ManualEmail
            //instance = new ManualEmail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ManualEmail
        /// </summary>
        [Test]
        public void ManualEmailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ManualEmail
            //Assert.IsInstanceOfType<ManualEmail> (instance, "variable 'instance' is a ManualEmail");
        }


        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'SenderId'
        /// </summary>
        [Test]
        public void SenderIdTest()
        {
            // TODO unit test for the property 'SenderId'
        }
        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [Test]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Test]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }
        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Test]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }
        /// <summary>
        /// Test the property 'ReplyToId'
        /// </summary>
        [Test]
        public void ReplyToIdTest()
        {
            // TODO unit test for the property 'ReplyToId'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'HtmlBody'
        /// </summary>
        [Test]
        public void HtmlBodyTest()
        {
            // TODO unit test for the property 'HtmlBody'
        }
        /// <summary>
        /// Test the property 'TextBody'
        /// </summary>
        [Test]
        public void TextBodyTest()
        {
            // TODO unit test for the property 'TextBody'
        }
        /// <summary>
        /// Test the property 'OpenTracking'
        /// </summary>
        [Test]
        public void OpenTrackingTest()
        {
            // TODO unit test for the property 'OpenTracking'
        }
        /// <summary>
        /// Test the property 'ClickTracking'
        /// </summary>
        [Test]
        public void ClickTrackingTest()
        {
            // TODO unit test for the property 'ClickTracking'
        }
        /// <summary>
        /// Test the property 'Attachment'
        /// </summary>
        [Test]
        public void AttachmentTest()
        {
            // TODO unit test for the property 'Attachment'
        }
        /// <summary>
        /// Test the property 'MergeTags'
        /// </summary>
        [Test]
        public void MergeTagsTest()
        {
            // TODO unit test for the property 'MergeTags'
        }
        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'Registered'
        /// </summary>
        [Test]
        public void RegisteredTest()
        {
            // TODO unit test for the property 'Registered'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Test]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

    }

}
