/* 
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IDomainsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create New Domain
        /// </summary>
        /// <remarks>
        /// Add a new Domain to the list of available Domains for the sender to the recipient.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>DomainResponse</returns>
        DomainResponse AddDomain (DomainRequest body = null);

        /// <summary>
        /// Create New Domain
        /// </summary>
        /// <remarks>
        /// Add a new Domain to the list of available Domains for the sender to the recipient.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of DomainResponse</returns>
        ApiResponse<DomainResponse> AddDomainWithHttpInfo (DomainRequest body = null);
        /// <summary>
        /// Change Default Domain
        /// </summary>
        /// <remarks>
        /// Change the currently configured default Domain
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>DomainResponse</returns>
        DomainResponse ChangeDefaultDomain (DefaultDomainRequest body = null);

        /// <summary>
        /// Change Default Domain
        /// </summary>
        /// <remarks>
        /// Change the currently configured default Domain
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of DomainResponse</returns>
        ApiResponse<DomainResponse> ChangeDefaultDomainWithHttpInfo (DefaultDomainRequest body = null);
        /// <summary>
        /// Get Default Domain
        /// </summary>
        /// <remarks>
        /// Retrieve the currently configured default Domain. If no default domain is set, the list will be empty.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>DomainResponse</returns>
        DomainResponse ListDefaultDomain ();

        /// <summary>
        /// Get Default Domain
        /// </summary>
        /// <remarks>
        /// Retrieve the currently configured default Domain. If no default domain is set, the list will be empty.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of DomainResponse</returns>
        ApiResponse<DomainResponse> ListDefaultDomainWithHttpInfo ();
        /// <summary>
        /// Get Single Domain
        /// </summary>
        /// <remarks>
        /// Retrieve the Domain with the id in the path.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Verify Request</param>
        /// <returns>DomainResponse</returns>
        DomainResponse ListDomain (string id);

        /// <summary>
        /// Get Single Domain
        /// </summary>
        /// <remarks>
        /// Retrieve the Domain with the id in the path.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Verify Request</param>
        /// <returns>ApiResponse of DomainResponse</returns>
        ApiResponse<DomainResponse> ListDomainWithHttpInfo (string id);
        /// <summary>
        /// Get All Domains
        /// </summary>
        /// <remarks>
        /// Retrieve the list of all Domains available for the sender to the recipients.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;DomainResponse&gt;</returns>
        List<DomainResponse> ListDomains ();

        /// <summary>
        /// Get All Domains
        /// </summary>
        /// <remarks>
        /// Retrieve the list of all Domains available for the sender to the recipients.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;DomainResponse&gt;</returns>
        ApiResponse<List<DomainResponse>> ListDomainsWithHttpInfo ();
        /// <summary>
        /// Validate Single Domain
        /// </summary>
        /// <remarks>
        /// Clears the validation cache and validates the supplied configured Domain.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Domain</param>
        /// <returns>ValidateDomainResponse</returns>
        ValidateDomainResponse ValidateDomain (string id);

        /// <summary>
        /// Validate Single Domain
        /// </summary>
        /// <remarks>
        /// Clears the validation cache and validates the supplied configured Domain.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Domain</param>
        /// <returns>ApiResponse of ValidateDomainResponse</returns>
        ApiResponse<ValidateDomainResponse> ValidateDomainWithHttpInfo (string id);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create New Domain
        /// </summary>
        /// <remarks>
        /// Add a new Domain to the list of available Domains for the sender to the recipient.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of DomainResponse</returns>
        System.Threading.Tasks.Task<DomainResponse> AddDomainAsync (DomainRequest body = null);

        /// <summary>
        /// Create New Domain
        /// </summary>
        /// <remarks>
        /// Add a new Domain to the list of available Domains for the sender to the recipient.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (DomainResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DomainResponse>> AddDomainAsyncWithHttpInfo (DomainRequest body = null);
        /// <summary>
        /// Change Default Domain
        /// </summary>
        /// <remarks>
        /// Change the currently configured default Domain
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of DomainResponse</returns>
        System.Threading.Tasks.Task<DomainResponse> ChangeDefaultDomainAsync (DefaultDomainRequest body = null);

        /// <summary>
        /// Change Default Domain
        /// </summary>
        /// <remarks>
        /// Change the currently configured default Domain
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (DomainResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DomainResponse>> ChangeDefaultDomainAsyncWithHttpInfo (DefaultDomainRequest body = null);
        /// <summary>
        /// Get Default Domain
        /// </summary>
        /// <remarks>
        /// Retrieve the currently configured default Domain. If no default domain is set, the list will be empty.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of DomainResponse</returns>
        System.Threading.Tasks.Task<DomainResponse> ListDefaultDomainAsync ();

        /// <summary>
        /// Get Default Domain
        /// </summary>
        /// <remarks>
        /// Retrieve the currently configured default Domain. If no default domain is set, the list will be empty.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (DomainResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DomainResponse>> ListDefaultDomainAsyncWithHttpInfo ();
        /// <summary>
        /// Get Single Domain
        /// </summary>
        /// <remarks>
        /// Retrieve the Domain with the id in the path.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Verify Request</param>
        /// <returns>Task of DomainResponse</returns>
        System.Threading.Tasks.Task<DomainResponse> ListDomainAsync (string id);

        /// <summary>
        /// Get Single Domain
        /// </summary>
        /// <remarks>
        /// Retrieve the Domain with the id in the path.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Verify Request</param>
        /// <returns>Task of ApiResponse (DomainResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DomainResponse>> ListDomainAsyncWithHttpInfo (string id);
        /// <summary>
        /// Get All Domains
        /// </summary>
        /// <remarks>
        /// Retrieve the list of all Domains available for the sender to the recipients.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;DomainResponse&gt;</returns>
        System.Threading.Tasks.Task<List<DomainResponse>> ListDomainsAsync ();

        /// <summary>
        /// Get All Domains
        /// </summary>
        /// <remarks>
        /// Retrieve the list of all Domains available for the sender to the recipients.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;DomainResponse&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<DomainResponse>>> ListDomainsAsyncWithHttpInfo ();
        /// <summary>
        /// Validate Single Domain
        /// </summary>
        /// <remarks>
        /// Clears the validation cache and validates the supplied configured Domain.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Domain</param>
        /// <returns>Task of ValidateDomainResponse</returns>
        System.Threading.Tasks.Task<ValidateDomainResponse> ValidateDomainAsync (string id);

        /// <summary>
        /// Validate Single Domain
        /// </summary>
        /// <remarks>
        /// Clears the validation cache and validates the supplied configured Domain.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Domain</param>
        /// <returns>Task of ApiResponse (ValidateDomainResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ValidateDomainResponse>> ValidateDomainAsyncWithHttpInfo (string id);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class DomainsApi : IDomainsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DomainsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class
        /// </summary>
        /// <returns></returns>
        public DomainsApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DomainsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create New Domain Add a new Domain to the list of available Domains for the sender to the recipient.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>DomainResponse</returns>
        public DomainResponse AddDomain (DomainRequest body = null)
        {
             ApiResponse<DomainResponse> localVarResponse = AddDomainWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create New Domain Add a new Domain to the list of available Domains for the sender to the recipient.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of DomainResponse</returns>
        public ApiResponse< DomainResponse > AddDomainWithHttpInfo (DomainRequest body = null)
        {

            var localVarPath = "/v2/domain";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainResponse)));
        }

        /// <summary>
        /// Create New Domain Add a new Domain to the list of available Domains for the sender to the recipient.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of DomainResponse</returns>
        public async System.Threading.Tasks.Task<DomainResponse> AddDomainAsync (DomainRequest body = null)
        {
             ApiResponse<DomainResponse> localVarResponse = await AddDomainAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create New Domain Add a new Domain to the list of available Domains for the sender to the recipient.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (DomainResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DomainResponse>> AddDomainAsyncWithHttpInfo (DomainRequest body = null)
        {

            var localVarPath = "/v2/domain";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainResponse)));
        }

        /// <summary>
        /// Change Default Domain Change the currently configured default Domain
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>DomainResponse</returns>
        public DomainResponse ChangeDefaultDomain (DefaultDomainRequest body = null)
        {
             ApiResponse<DomainResponse> localVarResponse = ChangeDefaultDomainWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Change Default Domain Change the currently configured default Domain
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of DomainResponse</returns>
        public ApiResponse< DomainResponse > ChangeDefaultDomainWithHttpInfo (DefaultDomainRequest body = null)
        {

            var localVarPath = "/v2/domain/default";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ChangeDefaultDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainResponse)));
        }

        /// <summary>
        /// Change Default Domain Change the currently configured default Domain
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of DomainResponse</returns>
        public async System.Threading.Tasks.Task<DomainResponse> ChangeDefaultDomainAsync (DefaultDomainRequest body = null)
        {
             ApiResponse<DomainResponse> localVarResponse = await ChangeDefaultDomainAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Change Default Domain Change the currently configured default Domain
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (DomainResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DomainResponse>> ChangeDefaultDomainAsyncWithHttpInfo (DefaultDomainRequest body = null)
        {

            var localVarPath = "/v2/domain/default";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ChangeDefaultDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainResponse)));
        }

        /// <summary>
        /// Get Default Domain Retrieve the currently configured default Domain. If no default domain is set, the list will be empty.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>DomainResponse</returns>
        public DomainResponse ListDefaultDomain ()
        {
             ApiResponse<DomainResponse> localVarResponse = ListDefaultDomainWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Default Domain Retrieve the currently configured default Domain. If no default domain is set, the list will be empty.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of DomainResponse</returns>
        public ApiResponse< DomainResponse > ListDefaultDomainWithHttpInfo ()
        {

            var localVarPath = "/v2/domain/default";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListDefaultDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainResponse)));
        }

        /// <summary>
        /// Get Default Domain Retrieve the currently configured default Domain. If no default domain is set, the list will be empty.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of DomainResponse</returns>
        public async System.Threading.Tasks.Task<DomainResponse> ListDefaultDomainAsync ()
        {
             ApiResponse<DomainResponse> localVarResponse = await ListDefaultDomainAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Default Domain Retrieve the currently configured default Domain. If no default domain is set, the list will be empty.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (DomainResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DomainResponse>> ListDefaultDomainAsyncWithHttpInfo ()
        {

            var localVarPath = "/v2/domain/default";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListDefaultDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainResponse)));
        }

        /// <summary>
        /// Get Single Domain Retrieve the Domain with the id in the path.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Verify Request</param>
        /// <returns>DomainResponse</returns>
        public DomainResponse ListDomain (string id)
        {
             ApiResponse<DomainResponse> localVarResponse = ListDomainWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Single Domain Retrieve the Domain with the id in the path.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Verify Request</param>
        /// <returns>ApiResponse of DomainResponse</returns>
        public ApiResponse< DomainResponse > ListDomainWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling DomainsApi->ListDomain");

            var localVarPath = "/v2/domain/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainResponse)));
        }

        /// <summary>
        /// Get Single Domain Retrieve the Domain with the id in the path.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Verify Request</param>
        /// <returns>Task of DomainResponse</returns>
        public async System.Threading.Tasks.Task<DomainResponse> ListDomainAsync (string id)
        {
             ApiResponse<DomainResponse> localVarResponse = await ListDomainAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Single Domain Retrieve the Domain with the id in the path.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Verify Request</param>
        /// <returns>Task of ApiResponse (DomainResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DomainResponse>> ListDomainAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling DomainsApi->ListDomain");

            var localVarPath = "/v2/domain/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainResponse)));
        }

        /// <summary>
        /// Get All Domains Retrieve the list of all Domains available for the sender to the recipients.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;DomainResponse&gt;</returns>
        public List<DomainResponse> ListDomains ()
        {
             ApiResponse<List<DomainResponse>> localVarResponse = ListDomainsWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get All Domains Retrieve the list of all Domains available for the sender to the recipients.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;DomainResponse&gt;</returns>
        public ApiResponse< List<DomainResponse> > ListDomainsWithHttpInfo ()
        {

            var localVarPath = "/v2/domain";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListDomains", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<DomainResponse>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<DomainResponse>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<DomainResponse>)));
        }

        /// <summary>
        /// Get All Domains Retrieve the list of all Domains available for the sender to the recipients.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;DomainResponse&gt;</returns>
        public async System.Threading.Tasks.Task<List<DomainResponse>> ListDomainsAsync ()
        {
             ApiResponse<List<DomainResponse>> localVarResponse = await ListDomainsAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get All Domains Retrieve the list of all Domains available for the sender to the recipients.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;DomainResponse&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<DomainResponse>>> ListDomainsAsyncWithHttpInfo ()
        {

            var localVarPath = "/v2/domain";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListDomains", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<DomainResponse>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<DomainResponse>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<DomainResponse>)));
        }

        /// <summary>
        /// Validate Single Domain Clears the validation cache and validates the supplied configured Domain.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Domain</param>
        /// <returns>ValidateDomainResponse</returns>
        public ValidateDomainResponse ValidateDomain (string id)
        {
             ApiResponse<ValidateDomainResponse> localVarResponse = ValidateDomainWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Validate Single Domain Clears the validation cache and validates the supplied configured Domain.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Domain</param>
        /// <returns>ApiResponse of ValidateDomainResponse</returns>
        public ApiResponse< ValidateDomainResponse > ValidateDomainWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling DomainsApi->ValidateDomain");

            var localVarPath = "/v2/domain/{id}/validate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ValidateDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ValidateDomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ValidateDomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidateDomainResponse)));
        }

        /// <summary>
        /// Validate Single Domain Clears the validation cache and validates the supplied configured Domain.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Domain</param>
        /// <returns>Task of ValidateDomainResponse</returns>
        public async System.Threading.Tasks.Task<ValidateDomainResponse> ValidateDomainAsync (string id)
        {
             ApiResponse<ValidateDomainResponse> localVarResponse = await ValidateDomainAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Validate Single Domain Clears the validation cache and validates the supplied configured Domain.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the Domain</param>
        /// <returns>Task of ApiResponse (ValidateDomainResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ValidateDomainResponse>> ValidateDomainAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling DomainsApi->ValidateDomain");

            var localVarPath = "/v2/domain/{id}/validate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarHeaderParams["ApiKey"] = this.Configuration.GetApiKeyWithPrefix("ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ValidateDomain", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ValidateDomainResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ValidateDomainResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidateDomainResponse)));
        }

    }
}
